# Connecting to GitHub
If running on Google Colab, the following will connect to GitHub and clone the repository.

In [ ]:
git_username = ''
git_token =  ''

if git_username == '':
  print('Github username:')
  git_username = %sx read -p ''
  git_username = git_username[0]

if git_token == '':
  print('Github access token (https://github.com/settings/tokens):')
  print('Github Token:')
  git_token = %sx read -p ''
  git_token = git_token[0]

In [ ]:
# Clone the entire repo.
%cd /content
!git clone -l -s https://$git_username:$git_token@github.com/lougau92/MA1-Development-of-XAI-based-framework-to-Understand-Predict-and-Link-Homicides.git research-project
%cd research-project
!ls
!git init

In [ ]:
# Update repo.
%cd /content
%cd research-project
!git pull
!ls

# Training Decision Trees

## 1) Imports

In [1]:
from sklearn.model_selection import cross_val_score, cross_val_predict, PredefinedSplit
from sklearn.metrics import confusion_matrix, make_scorer, classification_report, accuracy_score, balanced_accuracy_score, ConfusionMatrixDisplay
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import ParameterGrid, GridSearchCV, train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import plotly.figure_factory as ff
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
from typing import List
from preprocess import clean_dataframe, to_numeric, bin_age, get_train_test_val
import functions_dec_trees as fdt

## 2) Loading and transforming data

In [2]:
train_sample, test_sample, validation_sample = fdt.load_subsets()
ordinal_encoder_inputs = fdt.fit_Encoder_on_inputs()
ordinal_encoder_outputs = fdt.fit_Encoder_on_outputs()
train_sample = to_numeric(train_sample, ordinal_encoder = ordinal_encoder_inputs, non_numeric_features = fdt.non_numeric_inputs)
test_sample = to_numeric(test_sample, ordinal_encoder = ordinal_encoder_inputs, non_numeric_features = fdt.non_numeric_inputs)
validation_sample = to_numeric(validation_sample, ordinal_encoder = ordinal_encoder_inputs, non_numeric_features = fdt.non_numeric_inputs)

## 3) Finding optimal penalty parameter for tree pruning

In [ ]:
target_variable_5 = 'OffEthnic'

alpha_unweighted = fdt.find_pruning_parameter(fdt.input_features, target_variable_5, train_sample, test_sample)
alpha_weighted = fdt.find_pruning_parameter(fdt.input_features, target_variable_5, train_sample, test_sample, class_weights='balanced')

print(f'Best parameter for predicting {target_variable_5} without weights: {alpha_unweighted}.')
print(f'Best parameter for predicting {target_variable_5} with weights: {alpha_weighted}.')

Best parameter for predicting OffEthnic without weights: 0.0013096340000000003.
Best parameter for predicting OffEthnic with weights: 0.00027699699999999964.


## 4) Building the optimized trees

### 4.1) Single target model

For this model, we train six single-output decision trees, one for each output variable. A vector of the six predictions for one specific training/testing/validation instance is then considered as the multi-output prediction.

In [3]:
standard_trees_unweighted = {}
standard_trees_weighted = {}
reports_standard_unweighted = {}
reports_standard_weighted = {}
report_dicts_standard_unweighted = {}
report_dicts_standard_weighted = {}

standard_trees_unweighted, standard_trees_weighted = fdt.fit_all_trees(train_sample)
standard_trees_predictions_unweighted = fdt.predict_all(test_sample, trained_trees=standard_trees_unweighted)
standard_trees_predictions_weighted = fdt.predict_all(test_sample, trained_trees=standard_trees_weighted, class_weights='balanced')

for target_variable_4_1 in fdt.output_features:
    report_unweighted = classification_report(test_sample[target_variable_4_1], standard_trees_predictions_unweighted[target_variable_4_1+'_pred'], zero_division=0)
    report_weighted = classification_report(test_sample[target_variable_4_1], standard_trees_predictions_weighted[target_variable_4_1+'_pred'], zero_division=0)
    report_dict_unweighted = classification_report(test_sample[target_variable_4_1], standard_trees_predictions_unweighted[target_variable_4_1+'_pred'], output_dict=True, zero_division=0)
    report_dict_weighted = classification_report(test_sample[target_variable_4_1], standard_trees_predictions_weighted[target_variable_4_1+'_pred'], output_dict=True, zero_division=0)

    reports_standard_unweighted[target_variable_4_1] = report_unweighted
    reports_standard_weighted[target_variable_4_1] = report_weighted
    report_dicts_standard_unweighted[target_variable_4_1] = report_dict_unweighted
    report_dicts_standard_weighted[target_variable_4_1] = report_dict_weighted

# print report of trees for target_variable_4_1
target_variable_4_1 = 'OffSex'
print(f'Classification report for predicting {target_variable_4_1} without weights:')
print(f'{reports_standard_unweighted[target_variable_4_1]} \n')
print(f'Classification report for predicting {target_variable_4_1} with weights:')
print(reports_standard_weighted[target_variable_4_1])

Classification report for predicting OffEthnic without weights:
                        precision    recall  f1-score   support

       Hispanic origin       0.77      0.77      0.77      2724
Not of Hispanic origin       0.89      0.93      0.91      8804
               Unknown       0.99      0.97      0.98     16905

              accuracy                           0.94     28433
             macro avg       0.88      0.89      0.89     28433
          weighted avg       0.94      0.94      0.94     28433
 

Classification report for predicting OffEthnic with weights:
                        precision    recall  f1-score   support

       Hispanic origin       0.76      0.77      0.76      2724
Not of Hispanic origin       0.90      0.92      0.91      8804
               Unknown       0.99      0.97      0.98     16905

              accuracy                           0.94     28433
             macro avg       0.88      0.89      0.89     28433
          weighted avg       0.94   

### 4.2) Multi target stacking model

This model is similar to the first, but we train an additional six meta decision trees. These meta trees are given the predictions of the six single target trees as inputs in addition to the original input features.

In [6]:
meta_train_unweighted, meta_test_unweighted, meta_validation_unweighted = fdt.generate_data_for_meta_trees(standard_trees_unweighted, train_sample, test_sample, validation_sample, ordinal_encoder_outputs)
meta_train_weighted, meta_test_weighted, meta_validation_weighted = fdt.generate_data_for_meta_trees(standard_trees_weighted, train_sample, test_sample, validation_sample, ordinal_encoder_outputs)

meta_trees_unweighted, meta_trees_weighted = fdt.fit_all_trees(meta_train_unweighted, meta_train_data_weighted=meta_train_weighted, standard=False)

reports_meta_unweighted = {}
reports_meta_weighted = {}
report_dicts_meta_unweighted = {}
report_dicts_meta_weighted = {}

meta_trees_predictions_unweighted = fdt.predict_all(meta_test_unweighted, trained_trees=meta_trees_unweighted, standard=False)
meta_trees_predictions_weighted = fdt.predict_all(meta_test_weighted, trained_trees=meta_trees_weighted, standard=False, class_weights='balanced')

for target_variable_6 in fdt.output_features:
    report_unweighted = classification_report(meta_test_unweighted[target_variable_6], meta_trees_predictions_unweighted[target_variable_6+'_pred_meta'], zero_division=0)
    report_weighted = classification_report(meta_test_weighted[target_variable_6], meta_trees_predictions_weighted[target_variable_6+'_pred_meta'], zero_division=0)
    report_dict_unweighted = classification_report(meta_test_unweighted[target_variable_6], meta_trees_predictions_unweighted[target_variable_6+'_pred_meta'], output_dict=True, zero_division=0)
    report_dict_weighted = classification_report(meta_test_weighted[target_variable_6], meta_trees_predictions_weighted[target_variable_6+'_pred_meta'], output_dict=True, zero_division=0)

    reports_meta_unweighted[target_variable_6] = report_unweighted
    reports_meta_weighted[target_variable_6] = report_weighted
    report_dicts_meta_unweighted[target_variable_6] = report_dict_unweighted
    report_dicts_meta_weighted[target_variable_6] = report_dict_weighted

# print report of trees for target_variable_4_2
target_variable_4_2 = 'OffEthnic'
print(f'Classification report for predicting {target_variable_4_2} without weights:')
print(f'{reports_meta_unweighted[target_variable_4_2]} \n')
print(f'Classification report for predicting {target_variable_4_2} with weights:')
print(reports_meta_weighted[target_variable_4_2])

#meta_trees_weighted, alphas_meta_weighted = fdt.create_meta_trees(fdt.input_features, fdt.output_features, train_sample, test_sample, validation_sample, ordinal_encoder_outputs, class_weights='balanced', return_alphas=True)
#meta_trees_unweighted, alphas_meta_unweighted = fdt.create_meta_trees(fdt.input_features, fdt.output_features, train_sample, test_sample, validation_sample, ordinal_encoder_outputs, return_alphas=True)

Classification report for predicting OffEthnic without weights:
                        precision    recall  f1-score   support

       Hispanic origin       0.77      0.77      0.77      2724
Not of Hispanic origin       0.89      0.93      0.91      8804
               Unknown       0.99      0.97      0.98     16905

              accuracy                           0.94     28433
             macro avg       0.88      0.89      0.89     28433
          weighted avg       0.94      0.94      0.94     28433
 

Classification report for predicting OffEthnic with weights:
                        precision    recall  f1-score   support

       Hispanic origin       0.76      0.77      0.76      2724
Not of Hispanic origin       0.90      0.92      0.91      8804
               Unknown       0.99      0.97      0.98     16905

              accuracy                           0.94     28433
             macro avg       0.88      0.89      0.89     28433
          weighted avg       0.94   

## 5) Analyzing the individual trees

### 5.1) Depth of trees

In [9]:
for target_variable_7 in fdt.output_features:
    print(f'For feature {target_variable_7}')
    print(f'Length of standard, unweighted tree: {standard_trees_unweighted[target_variable_7].tree_.max_depth}')
    print(f'Length of standard, weighted tree: {standard_trees_weighted[target_variable_7].tree_.max_depth}')
    print()

For feature OffAge
Length of standard, unweighted tree: 5
Length of standard, weighted tree: 6

For feature OffSex
Length of standard, unweighted tree: 44
Length of standard, weighted tree: 9

For feature OffRace
Length of standard, unweighted tree: 4
Length of standard, weighted tree: 8

For feature OffEthnic
Length of standard, unweighted tree: 2
Length of standard, weighted tree: 8

For feature OffCount
Length of standard, unweighted tree: 45
Length of standard, weighted tree: 30

For feature Relationship
Length of standard, unweighted tree: 11
Length of standard, weighted tree: 10



### 5.2) Feature Importance Heatmaps

In [37]:
fdt.feature_importance_heatmap(standard_trees_unweighted)

### 5.3) Confusion matrices

In [44]:
target_variable_7 = 'OffEthnic'

conf_matrix_plot = fdt.plotly_confusion_matrix(test_sample[target_variable_7], standard_trees_unweighted[target_variable_7].predict(test_sample[fdt.input_features]), test_sample[target_variable_7].unique())
conf_matrix_plot.show()

Confusion matrix:
[[ 8156    88   560]
 [  366 16464    75]
 [  592    44  2088]]


### 5.4) Plotting metrics of trees

In [32]:
tree_names = ['Gender_unweighted', 'Gender-weighted']
tree_reports = [report_dicts_standard_unweighted['Relationship'], report_dicts_standard_weighted['Relationship']]

fig = fdt.plot_metrics(tree_names, tree_reports, 'Relationship')
fig.show()

### 5.5) Plotting graphs structures of trees

In [11]:
target_variable_7 = 'OffAge'

plt.figure(figsize=(6,6), dpi=3000)
plot_tree(
    standard_trees_unweighted[target_variable_7],
    #max_depth=10,
    feature_names=fdt.input_features,
    class_names=fdt.names[target_variable_7],
    filled=True
)
plt.show()

In [29]:
predicted_vs_real = fdt.predict_all(train_sample[fdt.input_features], train_sample[fdt.output_features], test_sample[fdt.input_features], test_sample[fdt.output_features])
sorted = predicted_vs_real.sort_values(by=['No_equals'], ascending=False)
sorted.head()
sorted.to_csv('predictions.csv')